/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatv1;

import java.awt.Color;
import java.awt.Image;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JViewport;

/**
 *
 * @author dii
 */
public class ChatFrame extends javax.swing.JFrame {

    static String log = "";
    static Random rng = new Random();
    static ImageIcon BG = new ImageIcon("resources\\chat"+rng.nextInt(10)+".jpg");
//    static Color b = new Color(0f, 0f, 0f, 0f);
    static Color c = new Color(1f, 1f, 1f,.4f);
    
//    static JTextArea logTA = new JTextArea();
    static JLabel bg = new JLabel();
    
    public ChatFrame() {
        
        initComponents();
        logTA.setBackground(c);
        logTA.setOpaque(true);
        logTA.setAutoscrolls(true);
        scrP.setBorder(null);
        bg.setIcon(BG);
        this.add(bg);
        repaint();
        scrP.getViewport().setScrollMode(JViewport.SIMPLE_SCROLL_MODE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InputTF = new javax.swing.JTextField();
        scrP = new javax.swing.JScrollPane();
        logTA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 405));
        setPreferredSize(new java.awt.Dimension(720, 405));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        InputTF.setText("Di aglo");
        InputTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputTFActionPerformed(evt);
            }
        });
        getContentPane().add(InputTF);
        InputTF.setBounds(20, 330, 670, 30);

        scrP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        scrP.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrP.setToolTipText("");
        scrP.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrP.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        scrP.setEnabled(false);
        scrP.setFocusable(false);
        scrP.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                scrPMouseWheelMoved(evt);
            }
        });

        logTA.setEditable(false);
        logTA.setColumns(20);
        logTA.setRows(5);
        logTA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        logTA.setFocusable(false);
        scrP.setViewportView(logTA);

        getContentPane().add(scrP);
        scrP.setBounds(20, 20, 670, 290);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputTFActionPerformed
        if (InputTF.getText().length()>0) {
            log += "<USER> " + InputTF.getText() + "\n";
            logTA.setText(log);
            InputTF.setText("");
            this.repaint();
            repaint();
            scrP.repaint();
        }
    }//GEN-LAST:event_InputTFActionPerformed

    private void scrPMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_scrPMouseWheelMoved
        // TODO add your handling code here:
        repaint();
    }//GEN-LAST:event_scrPMouseWheelMoved

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        bg.setBounds(0, 0, 720, 405);
        bg.setIcon(BG);
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatFrame().setVisible(true);
                
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InputTF;
    private javax.swing.JTextArea logTA;
    private javax.swing.JScrollPane scrP;
    // End of variables declaration//GEN-END:variables
}
