package chatv1;

import java.awt.Color;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JScrollPane;

public class Chat extends javax.swing.JFrame {

    static String log = "";
    static Random rng = new Random();
    static ImageIcon BG = new ImageIcon("D:\\ChatV1\\ChatV1\\src\\resources\\chat" + (rng.nextInt(10)) + ".jpg");
    static Color c = new Color(0f, 0f, 0f, .1f);
    static JLabel background = new JLabel();
    public Chat() {
        initComponents();
        this.setSize(720,435);
        this.setResizable(false);
        bG.setBounds(0,0,720,405);
        bG.setIcon(BG);
        this.add(bG);
        scrPane.setBackground(c);
        scrPane.setForeground(c);
//        JScrollPane scrPane = new JScrollPane(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS,
//                JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
//        scrPane.setBounds(10, 10, 700, 340);
////scrPane .getViewport().add( lab_test);
//        scrPane.add(logLabel);
//        scrPane.setVisible(true);
        inputTF.setBounds(10, 360, 700,30);
//        logLabel.setVisible(true);
//        this.add(scrPane);
        scrPane.setAutoscrolls(true);
//        scrPane.se
        inputTF.setVisible(true);
        this.add(inputTF);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrPane = new javax.swing.JScrollPane();
        logLabel = new javax.swing.JLabel();
        bG = new javax.swing.JLabel();
        inputTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        scrPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        scrPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrPane.setOpaque(false);

        logLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        logLabel.setAutoscrolls(true);
        logLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        logLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        scrPane.setViewportView(logLabel);
        logLabel.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(scrPane);
        scrPane.setBounds(10, 14, 660, 280);
        getContentPane().add(bG);
        bG.setBounds(0, 0, 720, 290);

        inputTF.setText("Di aglo...");
        inputTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTFActionPerformed(evt);
            }
        });
        getContentPane().add(inputTF);
        inputTF.setBounds(10, 310, 660, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTFActionPerformed
        // TODO add your handling code here:
        log += "[USER]" + inputTF.getText() + "<br>";
        logLabel.setText("<html><body>" + log + "</body></html>");
        inputTF.setText("");
    }//GEN-LAST:event_inputTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bG;
    private javax.swing.JTextField inputTF;
    private javax.swing.JLabel logLabel;
    private javax.swing.JScrollPane scrPane;
    // End of variables declaration//GEN-END:variables
}
